import { AIChatAgent } from '@cloudflare/ai-chat';
import { callable } from 'agents';
import { streamText, convertToModelMessages, isStepCount, type Tool } from 'ai';
import { createWorkersAI } from 'workers-ai-provider';
// `Env` is a global ambient type generated by `wrangler types` (see worker-configuration.d.ts).

const TOOL_RESULT_LIMIT = 12_000;
const sanitize = (s: string) => s.replace(/[\r\n]/g, ' ');
const DEFAULT_SYSTEM_PROMPT =
	'You are InsertaBot, a helpful AI assistant with access to tools via MCP servers.';

type ModelLane = 'research' | 'coding';

type WrappedTool = Tool<any, any>;

interface ChatAgentState {
	modelLane: ModelLane | 'auto';
}

interface ServerInfo {
	name: string;
	server_url: string;
}

const MODEL_LANES: Record<ModelLane, { modelId: string; options: Record<string, unknown> }> = {
	research: {
		modelId: '@cf/moonshotai/kimi-k2.6',
		options: {
			// kimi-k2.6 renamed enable_thinking → thinking; disable it to avoid the
			// 8005 "Internal server error" that triggers when the backend tries to stream
			// reasoning tokens through a path that isn't fully stable yet.
			chat_template_kwargs: { thinking: false },
		},
	},
	coding: {
		modelId: '@cf/moonshotai/kimi-k2.7-code',
		options: {},
	},
};

function inferLane(servers: ServerInfo[]): ModelLane {
	const isCodingServer = (s: ServerInfo) => /github/i.test(s.name) || /github/i.test(s.server_url);
	return servers.some(isCodingServer) ? 'coding' : 'research';
}

/** Fast path for small results; avoids full JSON.stringify for huge strings. */
function truncateToolResult(result: unknown): unknown {
	if (result === null || result === undefined) return result;

	if (typeof result === 'string') {
		return result.length <= TOOL_RESULT_LIMIT
			? result
			: `${result.slice(0, TOOL_RESULT_LIMIT)}\n…[truncated — response too large for model context]`;
	}

	// For objects, try to stringify without paying the full cost when too large.
	let text: string;
	try {
		text = JSON.stringify(result);
	} catch {
		const fallback = String(result);
		return fallback.length <= TOOL_RESULT_LIMIT
			? fallback
			: `${fallback.slice(0, TOOL_RESULT_LIMIT)}\n…[truncated — response too large for model context]`;
	}

	if (text.length <= TOOL_RESULT_LIMIT) return result;

	return {
		truncated: true,
		preview: text.slice(0, TOOL_RESULT_LIMIT),
		message: 'Tool result truncated — response too large for model context',
	};
}

export class ChatAgent extends AIChatAgent<Env, ChatAgentState> {
	// Wait for any MCP connections that are still restoring after DO
	// hibernation before running the chat turn. Without this, getAITools()
	// can return tool *schemas* whose underlying transport isn't ready yet,
	// and the second-or-later tool call fails silently inside execute().
	waitForMcpConnections: boolean | { timeout: number } = { timeout: 10_000 };

	initialState: ChatAgentState = { modelLane: 'auto' };

	// Cached wrapped tool set; invalidated whenever MCP servers are added/removed.
	private cachedTools: Record<string, WrappedTool> | null = null;
	private toolsDirty = true;

	// Provider instance is stable per Durable Object because `this.env.AI` is stable.
	private workersaiProvider = createWorkersAI({
		binding: this.env.AI,
		gateway: { id: 'insertabot-cfworker' },
	});

	/**
	 * Manually pin the model lane for this session, overriding inference
	 * from attached MCP servers. Pass 'auto' to revert to inference.
	 */
	@callable()
	setModelLane(lane: ModelLane | 'auto'): void {
		if (lane !== 'auto' && !(lane in MODEL_LANES)) {
			throw new Error(`Invalid model lane: "${lane}"`);
		}
		this.setState({ modelLane: lane });
	}

	/**
	 * Connect to an MCP server by URL.
	 * Exposed as an RPC method so the UI can call it directly.
	 *
	 * If a prior connection for the same name is stuck in FAILED, remove it
	 * before reconnecting.
	 */
	@callable()
	async addServer(name: string, url: string, token?: string): Promise<void> {
		try {
			new URL(url);
		} catch {
			throw new Error(`Invalid server URL: "${url}"`);
		}

		if (token) {
			try {
				new URL(token);
				// If this succeeds, the user pasted a URL into the token field
				throw new Error(
					'The access token field contains a URL. If your MCP server uses a query-parameter API key (e.g. ?tavilyApiKey=…), include it in the Server URL field and leave the token field empty.',
				);
			} catch (e) {
				// Re-throw our own validation error; ignore URL parse failures (expected for real tokens)
				if ((e as Error).message.startsWith('The access token field')) throw e;
			}
		}

		const existing = this.mcp.listServers().find((s) => s.name === name);
		if (existing) {
			const conn = this.mcp.mcpConnections[existing.id];
			if (conn?.connectionState === 'failed') {
				console.log(`[MCP] Clearing stale FAILED connection for "${sanitize(name)}" before retrying`);
				await this.removeMcpServer(existing.id);
			} else {
				console.log(`[MCP] Server "${sanitize(name)}" already connected; skipping`);
				return;
			}
		}

		await this.addMcpServer(name, url, {
			...(token ? { transport: { headers: { Authorization: `Bearer ${token}` } } } : {}),
		});
		this.toolsDirty = true;
		console.log(`[MCP] Connected to "${sanitize(name)}" at ${sanitize(url)}`);
	}

	/**
	 * Disconnect an MCP server by friendly name or id.
	 */
	@callable()
	async removeServer(nameOrId: string): Promise<void> {
		const server = this.mcp.listServers().find((s) => s.id === nameOrId || s.name === nameOrId);
		if (!server) {
			console.warn(`[MCP] removeServer: no server matching "${sanitize(nameOrId)}" found`);
			return;
		}
		await this.removeMcpServer(server.id);
		this.toolsDirty = true;
		console.log(`[MCP] Disconnected "${sanitize(server.name)}"`);
	}

	/** Build the wrapped tool set once, then cache until the tool set changes. */
	private buildTools(): Record<string, WrappedTool> {
		if (!this.toolsDirty && this.cachedTools) return this.cachedTools;

		const rawTools = this.mcp.getAITools();
		const entries = Object.entries(rawTools);
		const built = entries.length === 0 ? {} : Object.fromEntries(
			entries.map(([toolName, tool]: [string, any]) => {
				if (typeof tool?.execute !== 'function') {
					return [toolName, tool as WrappedTool];
				}
				return [
					toolName,
					{
						...tool,
						execute: async (args: unknown, opts: unknown) => {
							if (args === null || typeof args !== 'object' || Array.isArray(args)) {
								throw new Error(
									`Tool "${toolName}" received invalid arguments: expected a plain object`,
								);
							}
							const result = await tool.execute(args, opts);
							return truncateToolResult(result);
						},
					} as WrappedTool,
				];
			}),
		);

		this.cachedTools = Object.freeze(built);
		this.toolsDirty = false;
		return this.cachedTools;
	}

	/**
	 * Main chat handler.
	 * All connected MCP tools are exposed to the model.
	 */
	async onChatMessage(
		onFinish: Parameters<AIChatAgent<Env>['onChatMessage']>[0],
	) {
		const tools = this.buildTools();
		const hasTools = Object.keys(tools).length > 0;

		const lane = this.state.modelLane === 'auto' ? inferLane(this.mcp.listServers()) : this.state.modelLane;
		const { modelId, options } = MODEL_LANES[lane];

		const result = streamText({
			model: this.workersaiProvider(modelId, options),
			system: this.env.SYSTEM_PROMPT ?? DEFAULT_SYSTEM_PROMPT,
			messages: await convertToModelMessages(this.messages),
			// stopWhen must be set whenever tools are even *possible*, otherwise
			// ai@7 defaults to isStepCount(1) which terminates after the first
			// tool-call step — that's why "the AI only works for a singular
			// tool use before it stops responding". 5 multi-step rounds is a
			// safe default.
			...(hasTools ? { tools, stopWhen: isStepCount(5) } : {}),
			// Surface tool execution + provider errors to the UI stream instead
			// of letting them disappear into the void.
			onError({ error }) {
				console.error('[streamText error]', error);
			},
			onFinish,
		});

		return result.toUIMessageStreamResponse({
			// Send error details over the stream so the front-end can render
			// them. Without this, errors are replaced with a generic message
			// and the UI just stops.
			onError(error) {
				console.error('[uiMessageStream error]', error);
				return error instanceof Error ? error.message : String(error);
			},
		});
	}
}
