import { routeAgentRequest } from 'agents';
import { ChatAgent } from './lib/durable';
import { corsHeaders, errorMessage, jsonResponse } from './lib/utils';
// `Env` is a global ambient type generated by `wrangler types` (see worker-configuration.d.ts).

// Re-export the Durable Object class — required by wrangler
export { ChatAgent };

const VERSION = '0.2.0';

// Cache parsed package metadata for health checks to avoid repeated object creation
const HEALTH_CACHE = Object.freeze({
	status: 'ok',
	worker: 'insertabot-cfworker',
	version: VERSION,
});

function handleHealth(_request: Request, env: Env): Response {
	return jsonResponse(
		{
			...HEALTH_CACHE,
			timestamp: new Date().toISOString(),
			bindings: {
				ai: !!env.AI,
				chatAgent: !!env.ChatAgent,
			},
		},
		200,
		corsHeaders(),
	);
}

function handleOptions(request: Request): Response {
	const origin = request.headers.get('Origin') || '*';
	return new Response(null, {
		headers: {
			...corsHeaders(origin),
			'Access-Control-Max-Age': '86400',
			Vary: 'Origin',
		},
	});
}

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		const url = new URL(request.url);
		const pathname = url.pathname;
		const startTime = Date.now();

		function logResponse(response: Response, note?: string) {
			const duration = Date.now() - startTime;
			console.log(
				`[request] ${request.method} ${pathname} ${response.status}${note ? ` — ${note}` : ''} (${duration}ms)`,
			);
		}

		if (request.method === 'OPTIONS') {
			const res = handleOptions(request);
			logResponse(res, 'preflight');
			return res;
		}

		try {
			// Hand off to the Agents SDK first — handles WebSocket upgrades, agent RPC,
			// MCP OAuth callbacks, and all /agents/* routing automatically.
			const agentResponse = await routeAgentRequest(request, env);
			if (agentResponse) {
				logResponse(agentResponse, agentResponse.webSocket ? 'websocket' : 'agent');
				return agentResponse;
			}

			let response: Response;
			switch (pathname) {
				case '/health':
					response = handleHealth(request, env);
					break;
				case '/favicon.ico':
					response = new Response(null, { status: 204 });
					break;
				default:
					response = new Response('Not Found', { status: 404 });
			}
			logResponse(response);
			return response;
		} catch (err: unknown) {
			const message = errorMessage(err);
			console.error('Unhandled worker error:', err);
			const response = jsonResponse(
				{ error: 'Internal Server Error', detail: message },
				500,
				corsHeaders(),
			);
			logResponse(response, 'error');
			return response;
		}
	},
};
